"""initial_schema — Alembic baseline.

Baseline migration for the Memoria database. All existing tables were
created by raw SQL in ``memoria.db.repository._common.SCHEMA`` and are
now also represented as SQLAlchemy ORM models in ``memoria.db.models``.

This migration is intentionally empty: it records the schema state
without applying DDL. Use ``alembic stamp head`` on existing databases.

Future autogenerated migrations will capture real schema changes.
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e133d3269a0f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """No-op baseline. Existing schema is managed by raw SQL."""


def downgrade() -> None:
    """No-op baseline."""
