"""baseline full schema

Revision ID: 06884ebd4d17
Revises: e133d3269a0f
Create Date: 2026-08-01 14:31:46.740051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06884ebd4d17'
down_revision: Union[str, Sequence[str], None] = 'e133d3269a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', sa.Text(), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.create_index('idx_background_job_claim', ['status', 'available_at', 'lease_expires_at', 'created_at'], unique=False)

    op.create_table('data_migration',
    sa.Column('migration_key', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('applied_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('migration_key')
    )
    op.create_table('domain_event',
    sa.Column('sequence', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('aggregate_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('causation_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('group_thread_id', sa.Text(), nullable=True),
    sa.Column('source_turn_id', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('world_occurred_at', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('owner_user_id', 'aggregate_type', 'aggregate_id', 'aggregate_version')
    )
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.create_index('idx_domain_event_aggregate', ['owner_user_id', 'aggregate_type', 'aggregate_id', 'aggregate_version'], unique=False)
        batch_op.create_index('idx_domain_event_correlation', ['owner_user_id', 'correlation_id', 'sequence'], unique=False)
        batch_op.create_index('idx_domain_event_group_thread', ['owner_user_id', 'group_thread_id', 'sequence'], unique=False)
        batch_op.create_index('idx_domain_event_source_turn', ['owner_user_id', 'source_turn_id', 'sequence'], unique=False)

    op.create_table('event_context_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('context_data', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('progress', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('last_session_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'character_id', 'player_id')
    )
    with op.batch_alter_table('event_context_state', schema=None) as batch_op:
        batch_op.create_index('idx_event_context_lookup', ['character_id', 'player_id', 'status', 'updated_at'], unique=False)

    op.create_table('event_exclusive_group_guard',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('exclusive_group', sa.Text(), nullable=False),
    sa.Column('selected_event_id', sa.Text(), nullable=True),
    sa.Column('claim_token', sa.Text(), nullable=True),
    sa.Column('claim_expires_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'exclusive_group')
    )
    op.create_table('event_execution',
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('execution_key', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('effects_data', sa.Text(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('execution_id'),
    sa.UniqueConstraint('owner_user_id', 'event_id', 'execution_key')
    )
    with op.batch_alter_table('event_execution', schema=None) as batch_op:
        batch_op.create_index('idx_event_execution_metrics', ['owner_user_id', 'event_id', 'status', 'completed_at'], unique=False)

    op.create_table('event_execution_batch',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('execution_key', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('results_data', sa.Text(), nullable=False),
    sa.Column('deduplicated_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'execution_key')
    )
    op.create_table('event_schedule_state',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.Text(), nullable=True),
    sa.Column('next_due_real_at', sa.Text(), nullable=True),
    sa.Column('missed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_failed_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'character_id', 'player_id')
    )
    with op.batch_alter_table('event_schedule_state', schema=None) as batch_op:
        batch_op.create_index('idx_event_schedule_due', ['status', 'next_run_at'], unique=False)
        batch_op.create_index('idx_event_schedule_due_real', ['status', 'next_due_real_at'], unique=False)
        batch_op.create_index('idx_event_schedule_lease', ['status', 'lease_expires_at'], unique=False)

    op.create_table('event_template',
    sa.Column('template_id', sa.Text(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_config', sa.Text(), nullable=False),
    sa.Column('effects_config', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('event_trigger_guard',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('character_scope', sa.Text(), nullable=False),
    sa.Column('last_triggered_at', sa.Text(), nullable=True),
    sa.Column('claim_token', sa.Text(), nullable=True),
    sa.Column('claim_expires_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'event_id', 'character_scope')
    )
    op.create_table('event_unlock',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('unlock_key', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('unlocked_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'character_id', 'unlock_key')
    )
    with op.batch_alter_table('event_unlock', schema=None) as batch_op:
        batch_op.create_index('idx_event_unlock_lookup', ['player_id', 'character_id', 'unlocked_at'], unique=False)

    op.create_table('fact_claim',
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('normalized_fact_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('normalized_content_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source_ids', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('supersedes_claim_id', sa.Text(), nullable=True),
    sa.Column('superseded_by_claim_id', sa.Text(), nullable=True),
    sa.Column('ledger_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.Text(), nullable=True),
    sa.Column('retracted_at', sa.Text(), nullable=True),
    sa.CheckConstraint("scope_type IN ('character', 'group_thread', 'story')"),
    sa.CheckConstraint("source_kind IN ('player_message', 'knowledge_chunk', 'authored_event', 'model_inference', 'legacy')"),
    sa.CheckConstraint("status IN ('candidate', 'verified', 'retracted', 'superseded')"),
    sa.ForeignKeyConstraint(['superseded_by_claim_id'], ['fact_claim.claim_id'], ),
    sa.ForeignKeyConstraint(['supersedes_claim_id'], ['fact_claim.claim_id'], ),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('owner_user_id', 'scope_type', 'scope_id', 'normalized_content_hash')
    )
    with op.batch_alter_table('fact_claim', schema=None) as batch_op:
        batch_op.create_index('idx_fact_claim_scope', ['owner_user_id', 'scope_type', 'scope_id', 'created_at', 'claim_id'], unique=False)
        batch_op.create_index('idx_fact_claim_verified', ['owner_user_id', 'scope_type', 'scope_id', 'status', 'created_at', 'claim_id'], unique=False)

    op.create_table('group_memory',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_referenced', sa.Text(), nullable=True),
    sa.Column('reference_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_vector_cleanup',
    sa.Column('cleanup_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('cleanup_id'),
    sa.UniqueConstraint('owner_user_id', 'scope_type', 'scope_id')
    )
    with op.batch_alter_table('knowledge_vector_cleanup', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_vector_cleanup_pending', ['updated_at', 'attempts'], unique=False)

    op.create_table('long_term_fact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_referenced', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('long_term_fact', schema=None) as batch_op:
        batch_op.create_index('idx_fact_lookup', ['character_id', 'player_id', 'importance', 'last_referenced'], unique=False)

    op.create_table('memory_curve_state',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('anchor_strength', sa.Float(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('stability_days', sa.Float(), nullable=False),
    sa.Column('anchor_elapsed_seconds', sa.Float(), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('elapsed_decay_seconds', sa.Float(), server_default=sa.text('(0.0)'), nullable=False),
    sa.Column('world_time_watermark', sa.Text(), nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_kind', sa.Text(), server_default=sa.text("'legacy'"), nullable=False),
    sa.Column('importance', sa.Float(), server_default=sa.text('(0.5)'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('owner_user_id', 'character_id', 'memory_type', 'memory_id')
    )
    with op.batch_alter_table('memory_curve_state', schema=None) as batch_op:
        batch_op.create_index('idx_memory_curve_character', ['owner_user_id', 'character_id', 'memory_type'], unique=False)

    op.create_table('projection_checkpoint',
    sa.Column('projector_name', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('last_sequence', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('projector_name', 'owner_user_id')
    )
    op.create_table('relationship_state',
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('affection_level', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('trust_level', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('current_mood', sa.Text(), server_default=sa.text("'neutral'"), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('character_id', 'player_id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('group_thread_id', sa.Text(), nullable=True),
    sa.Column('story_id', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), server_default=sa.text("'zh-CN'"), nullable=False),
    sa.Column('is_multi_character', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index('idx_session_group_thread', ['group_thread_id', 'created_at'], unique=False)
        batch_op.create_index('idx_session_lookup', ['character_id', 'player_id', 'created_at'], unique=False)
        batch_op.create_index('idx_session_multi', ['is_multi_character', 'player_id', 'created_at'], unique=False)

    op.create_table('shared_memory',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_a_id', sa.Text(), nullable=False),
    sa.Column('character_b_id', sa.Text(), nullable=False),
    sa.Column('observer_character_id', sa.Text(), nullable=True),
    sa.Column('target_character_id', sa.Text(), nullable=True),
    sa.Column('memory_kind', sa.Text(), server_default=sa.text("'legacy_archived'"), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_referenced', sa.Text(), nullable=True),
    sa.Column('reference_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_memory', schema=None) as batch_op:
        batch_op.create_index('idx_shared_memory_directional', ['owner_user_id', 'observer_character_id', 'target_character_id', 'importance'], unique=False)
        batch_op.create_index('idx_shared_memory_owner_pair', ['owner_user_id', 'character_a_id', 'character_b_id', 'importance'], unique=False)

    op.create_table('short_term_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=True),
    sa.Column('character_name', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('affinity_delta', sa.Float(), nullable=True),
    sa.Column('trust_delta', sa.Float(), nullable=True),
    sa.Column('current_affinity', sa.Float(), nullable=True),
    sa.Column('current_trust', sa.Float(), nullable=True),
    sa.Column('current_mood', sa.Text(), nullable=True),
    sa.Column('event_notification', sa.Text(), nullable=True),
    sa.Column('knowledge_sources', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_character_id', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('trigger_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('world_created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_term_message', schema=None) as batch_op:
        batch_op.create_index('idx_message_character', ['session_id', 'character_id', 'created_at'], unique=False)
        batch_op.create_index('idx_message_session', ['session_id', 'id'], unique=False)

    op.create_table('story_state',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('story_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('terminal_reason', sa.Text(), nullable=True),
    sa.Column('ledger_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'failed')"),
    sa.PrimaryKeyConstraint('owner_user_id', 'story_id')
    )
    with op.batch_alter_table('story_state', schema=None) as batch_op:
        batch_op.create_index('idx_story_state_status', ['owner_user_id', 'status', 'updated_at', 'story_id'], unique=False)

    op.create_table('system_bootstrap_claim',
    sa.Column('claim_key', sa.Text(), nullable=False),
    sa.Column('claimed_by_user_id', sa.Text(), nullable=False),
    sa.Column('claimed_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('claim_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gender', sa.Text(), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('tts_auto_play', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stt_auto_send', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_token',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.create_index('idx_auth_token_user', ['user_id', 'expires_at'], unique=False)

    op.create_table('character_card',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('card_data', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), server_default=sa.text("'1.0.0'"), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('avatar_revision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'db'"), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('owner_user_id', 'character_id')
    )
    with op.batch_alter_table('character_card', schema=None) as batch_op:
        batch_op.create_index('idx_character_active', ['owner_user_id', 'is_active', 'created_at'], unique=False)

    op.create_table('character_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_id_a', sa.Text(), nullable=False),
    sa.Column('character_id_b', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=True),
    sa.Column('affinity', sa.Float(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'character_id_a', 'character_id_b')
    )
    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.create_index('idx_relationship_lookup', ['owner_user_id', 'character_id_a', 'character_id_b'], unique=False)

    op.create_table('character_relationship_revision',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_id_a', sa.Text(), nullable=False),
    sa.Column('character_id_b', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('owner_user_id', 'character_id_a', 'character_id_b')
    )
    with op.batch_alter_table('character_relationship_revision', schema=None) as batch_op:
        batch_op.create_index('idx_relationship_revision_lookup', ['owner_user_id', 'character_id_a', 'character_id_b'], unique=False)

    op.create_table('dialogue_turn',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('turn_kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.Text(), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'request_id')
    )
    with op.batch_alter_table('dialogue_turn', schema=None) as batch_op:
        batch_op.create_index('idx_dialogue_turn_session_lease', ['session_id', 'status', 'lease_expires_at'], unique=False)

    op.create_table('event_definition',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Text(), nullable=True),
    sa.Column('story_id', sa.Text(), nullable=True),
    sa.Column('trigger_config', sa.Text(), nullable=False),
    sa.Column('effects_config', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('exclusive_group', sa.Text(), nullable=True),
    sa.Column('exclusive_scope', sa.Text(), server_default=sa.text("'turn'"), nullable=False),
    sa.Column('max_triggers_per_turn', sa.Integer(), server_default=sa.text('3'), nullable=True),
    sa.Column('stop_processing', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_triggered_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('owner_user_id', 'event_id')
    )
    with op.batch_alter_table('event_definition', schema=None) as batch_op:
        batch_op.create_index('idx_event_character', ['owner_user_id', 'character_id', 'is_active'], unique=False)

    op.create_table('group_dialogue_state',
    sa.Column('group_thread_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('current_topic', sa.Text(), nullable=True),
    sa.Column('topic_source', sa.Text(), nullable=True),
    sa.Column('last_reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('last_reply_to_character_id', sa.Text(), nullable=True),
    sa.Column('last_speaker_id', sa.Text(), nullable=True),
    sa.Column('waiting_for_player', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unresolved_hooks', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('last_autonomous_pulse_at', sa.Text(), nullable=True),
    sa.Column('last_autonomous_world_at', sa.Text(), nullable=True),
    sa.Column('daily_message_date', sa.Text(), nullable=True),
    sa.Column('daily_message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('group_thread_id')
    )
    with op.batch_alter_table('group_dialogue_state', schema=None) as batch_op:
        batch_op.create_index('idx_group_dialogue_state_scan', ['player_id', 'lease_expires_at', 'last_autonomous_pulse_at'], unique=False)

    op.create_table('knowledge_base',
    sa.Column('knowledge_base_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('knowledge_base_id')
    )
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_base_owner', ['owner_user_id', 'is_enabled', 'updated_at'], unique=False)

    op.create_table('memory_curve_reinforcement',
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('world_occurred_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id', 'character_id', 'memory_type', 'memory_id'], ['memory_curve_state.owner_user_id', 'memory_curve_state.character_id', 'memory_curve_state.memory_type', 'memory_curve_state.memory_id'], ),
    sa.PrimaryKeyConstraint('owner_user_id', 'character_id', 'memory_type', 'memory_id', 'evidence_id')
    )
    op.create_table('multi_session_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('join_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('speak_frequency', sa.Float(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('last_spoke_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'character_id')
    )
    with op.batch_alter_table('multi_session_participant', schema=None) as batch_op:
        batch_op.create_index('idx_multi_participant', ['session_id', 'is_active'], unique=False)

    op.create_table('player_event_inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), server_default=sa.text("'event'"), nullable=False),
    sa.Column('group_thread_id', sa.Text(), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('world_created_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('read_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_event_inbox', schema=None) as batch_op:
        batch_op.create_index('idx_player_event_inbox_unread', ['player_id', 'read_at', 'id'], unique=False)
        batch_op.create_index('idx_player_group_inbox_unread', ['player_id', 'group_thread_id', 'read_at', 'id'], unique=False)
    # 运行时由 init_db 创建的部分唯一索引（models.py 之外），迁移需保持一致
    op.create_index(
        'idx_inbox_group_unread',
        'player_event_inbox',
        ['player_id', 'group_thread_id'],
        unique=True,
        sqlite_where=sa.text("event_type = 'group_message' AND read_at IS NULL"),
        postgresql_where=sa.text("event_type = 'group_message' AND read_at IS NULL"),
    )

    op.create_table('player_world_clock',
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('timezone_mode', sa.Text(), server_default=sa.text("'fixed'"), nullable=False),
    sa.Column('anchor_real_utc', sa.Text(), nullable=False),
    sa.Column('anchor_world_utc', sa.Text(), nullable=False),
    sa.Column('time_scale', sa.Float(), server_default=sa.text('1'), nullable=False),
    sa.Column('clock_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('session_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('summary_status', sa.Text(), server_default=sa.text("'completed'"), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_summary', schema=None) as batch_op:
        batch_op.create_index('idx_summary_lookup', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('idx_summary_player', ['character_id', 'player_id', 'created_at'], unique=False)
        # 运行时由 init_db 创建的唯一索引（models.py 之外），迁移需保持一致
        batch_op.create_index('idx_summary_unique', ['session_id', 'character_id', 'player_id'], unique=True)

    op.create_table('user_character_card',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('pronouns', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('species', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('occupation', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('appearance', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('personality', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('background', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('goals', sa.Text(), server_default=sa.text("('')"), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('event_trigger_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('effects_applied', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'succeeded'"), nullable=True),
    sa.ForeignKeyConstraint(['player_id', 'event_id'], ['event_definition.owner_user_id', 'event_definition.event_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_trigger_log', schema=None) as batch_op:
        batch_op.create_index('idx_event_trigger_log', ['event_id', 'character_id', 'player_id', 'triggered_at'], unique=False)

    op.create_table('knowledge_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('knowledge_base_id', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.knowledge_base_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'knowledge_base_id', 'target_type', 'target_id')
    )
    with op.batch_alter_table('knowledge_binding', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_binding_target', ['owner_user_id', 'target_type', 'target_id', 'knowledge_base_id'], unique=False)

    op.create_table('knowledge_document',
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('knowledge_base_id', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_chars', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.knowledge_base_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_document_base', ['owner_user_id', 'knowledge_base_id', 'status', 'created_at'], unique=False)

    op.create_table('knowledge_chunk',
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('knowledge_base_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_document.document_id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.knowledge_base_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index('idx_knowledge_chunk_document', ['owner_user_id', 'document_id', 'chunk_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_chunk_document')

    op.drop_table('knowledge_chunk')
    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_document_base')

    op.drop_table('knowledge_document')
    with op.batch_alter_table('knowledge_binding', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_binding_target')

    op.drop_table('knowledge_binding')
    with op.batch_alter_table('event_trigger_log', schema=None) as batch_op:
        batch_op.drop_index('idx_event_trigger_log')

    op.drop_table('event_trigger_log')
    op.drop_table('user_character_card')
    with op.batch_alter_table('session_summary', schema=None) as batch_op:
        batch_op.drop_index('idx_summary_unique')
        batch_op.drop_index('idx_summary_player')
        batch_op.drop_index('idx_summary_lookup')

    op.drop_table('session_summary')
    op.drop_table('player_world_clock')
    op.drop_index('idx_inbox_group_unread', table_name='player_event_inbox')
    with op.batch_alter_table('player_event_inbox', schema=None) as batch_op:
        batch_op.drop_index('idx_player_group_inbox_unread')
        batch_op.drop_index('idx_player_event_inbox_unread')

    op.drop_table('player_event_inbox')
    with op.batch_alter_table('multi_session_participant', schema=None) as batch_op:
        batch_op.drop_index('idx_multi_participant')

    op.drop_table('multi_session_participant')
    op.drop_table('memory_curve_reinforcement')
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_base_owner')

    op.drop_table('knowledge_base')
    with op.batch_alter_table('group_dialogue_state', schema=None) as batch_op:
        batch_op.drop_index('idx_group_dialogue_state_scan')

    op.drop_table('group_dialogue_state')
    with op.batch_alter_table('event_definition', schema=None) as batch_op:
        batch_op.drop_index('idx_event_character')

    op.drop_table('event_definition')
    with op.batch_alter_table('dialogue_turn', schema=None) as batch_op:
        batch_op.drop_index('idx_dialogue_turn_session_lease')

    op.drop_table('dialogue_turn')
    with op.batch_alter_table('character_relationship_revision', schema=None) as batch_op:
        batch_op.drop_index('idx_relationship_revision_lookup')

    op.drop_table('character_relationship_revision')
    with op.batch_alter_table('character_relationship', schema=None) as batch_op:
        batch_op.drop_index('idx_relationship_lookup')

    op.drop_table('character_relationship')
    with op.batch_alter_table('character_card', schema=None) as batch_op:
        batch_op.drop_index('idx_character_active')

    op.drop_table('character_card')
    with op.batch_alter_table('auth_token', schema=None) as batch_op:
        batch_op.drop_index('idx_auth_token_user')

    op.drop_table('auth_token')
    op.drop_table('users')
    op.drop_table('system_bootstrap_claim')
    with op.batch_alter_table('story_state', schema=None) as batch_op:
        batch_op.drop_index('idx_story_state_status')

    op.drop_table('story_state')
    with op.batch_alter_table('short_term_message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_session')
        batch_op.drop_index('idx_message_character')

    op.drop_table('short_term_message')
    with op.batch_alter_table('shared_memory', schema=None) as batch_op:
        batch_op.drop_index('idx_shared_memory_owner_pair')
        batch_op.drop_index('idx_shared_memory_directional')

    op.drop_table('shared_memory')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index('idx_session_multi')
        batch_op.drop_index('idx_session_lookup')
        batch_op.drop_index('idx_session_group_thread')

    op.drop_table('session')
    op.drop_table('relationship_state')
    op.drop_table('projection_checkpoint')
    with op.batch_alter_table('memory_curve_state', schema=None) as batch_op:
        batch_op.drop_index('idx_memory_curve_character')

    op.drop_table('memory_curve_state')
    with op.batch_alter_table('long_term_fact', schema=None) as batch_op:
        batch_op.drop_index('idx_fact_lookup')

    op.drop_table('long_term_fact')
    with op.batch_alter_table('knowledge_vector_cleanup', schema=None) as batch_op:
        batch_op.drop_index('idx_knowledge_vector_cleanup_pending')

    op.drop_table('knowledge_vector_cleanup')
    op.drop_table('group_memory')
    with op.batch_alter_table('fact_claim', schema=None) as batch_op:
        batch_op.drop_index('idx_fact_claim_verified')
        batch_op.drop_index('idx_fact_claim_scope')

    op.drop_table('fact_claim')
    with op.batch_alter_table('event_unlock', schema=None) as batch_op:
        batch_op.drop_index('idx_event_unlock_lookup')

    op.drop_table('event_unlock')
    op.drop_table('event_trigger_guard')
    op.drop_table('event_template')
    with op.batch_alter_table('event_schedule_state', schema=None) as batch_op:
        batch_op.drop_index('idx_event_schedule_lease')
        batch_op.drop_index('idx_event_schedule_due_real')
        batch_op.drop_index('idx_event_schedule_due')

    op.drop_table('event_schedule_state')
    op.drop_table('event_execution_batch')
    with op.batch_alter_table('event_execution', schema=None) as batch_op:
        batch_op.drop_index('idx_event_execution_metrics')

    op.drop_table('event_execution')
    op.drop_table('event_exclusive_group_guard')
    with op.batch_alter_table('event_context_state', schema=None) as batch_op:
        batch_op.drop_index('idx_event_context_lookup')

    op.drop_table('event_context_state')
    with op.batch_alter_table('domain_event', schema=None) as batch_op:
        batch_op.drop_index('idx_domain_event_source_turn')
        batch_op.drop_index('idx_domain_event_group_thread')
        batch_op.drop_index('idx_domain_event_correlation')
        batch_op.drop_index('idx_domain_event_aggregate')

    op.drop_table('domain_event')
    op.drop_table('data_migration')
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.drop_index('idx_background_job_claim')

    op.drop_table('background_job')
    # ### end Alembic commands ###
